2025-04-20 19:36:12:3612 [31merror[39m: [31mError connecting to the database: no existe la base de datos ï¿½secure_authï¿½[39m
